# Generated by Django 3.2.4 on 2021-06-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemed', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
